-- SQL support (vim-dadbod / vim-dadbod-ui / vim-dadbod-completion) is now
-- declared and lazy-loaded in lua/plugins.lua via lazy.nvim (ft = sql/mysql/plsql,
-- cmd = DBUI...). This module is intentionally left empty and is no longer
-- required from init.lua.
