# USGC POLYMINIMAL — POLYIMIDE × minimal custom variant
background = #050505
# background = #191820
foreground = #DDDDDD
cursor-color = #FFBF00
cursor-text = #191820
selection-background = #454057
selection-foreground = #FFFFFF
palette = 0=#000000
palette = 1=#EC8FB0
palette = 2=#00FFAA
palette = 3=#FFBF00
palette = 4=#5CBCD6
palette = 5=#CDC1FF
palette = 6=#7E86B4
palette = 7=#DDDDDD
palette = 8=#403833
palette = 9=#E8838F
palette = 10=#00FFAA
palette = 11=#FFD166
palette = 12=#7AA2FF
palette = 13=#AD99FF
palette = 14=#7E86B4
palette = 15=#A8A8A8
